// Netlify Serverless Function: subscribe.js
// Handles newsletter signups for emevidence.org
// Adds contacts to Loops.so with correct list memberships,
// then triggers the welcome transactional email automatically.
//
// Environment variable required (set in Netlify UI):
//   LOOPS_API_KEY  — your Loops.so API key

// ── Loops config ────────────────────────────────────────────
const LOOPS_API   = "https://api.loops.so/v1";
const WELCOME_ID  = "cmpy5ftku03bf0jykghy0jz0f"; // Welcome to EM Evidence transactional email

// List IDs
const LISTS = {
  "Weekly EM Evidence Updates":                  "cmpy5zd8u4kzv8j1a9emeip31",
  "Monthly PHEM Evidence Updates":               "cmpy60jzs05gt0jzi26tj1acx",
  "Monthly Anaesthetics and ICM Evidence Updates": "cmpy6170t05ob0j0cfkut3vio",
  "Website Updates":                             "cmpy61pvr05uz0j0efg7c20v5",
};

// Contact property keys (auto-generated by Loops from labels)
const PROPS = {
  "Weekly EM Evidence Updates":                  "weeklyEmEvidence",
  "Monthly PHEM Evidence Updates":               "monthlyPhem",
  "Monthly Anaesthetics and ICM Evidence Updates": "monthlyAnaestheticsIcm",
  "Website Updates":                             "websiteUpdates",
};

// ── Helper: call Loops API ───────────────────────────────────
async function loopsPost(path, body, apiKey) {
  const https = require("https");
  const data  = JSON.stringify(body);

  return new Promise((resolve, reject) => {
    const req = https.request(
      {
        hostname: "api.loops.so",
        path:     `/v1${path}`,
        method:   "POST",
        headers:  {
          "Authorization": `Bearer ${apiKey}`,
          "Content-Type":  "application/json",
          "Content-Length": Buffer.byteLength(data),
        },
      },
      (res) => {
        let raw = "";
        res.on("data", (c) => (raw += c));
        res.on("end", () => {
          try { resolve({ status: res.statusCode, body: JSON.parse(raw) }); }
          catch { resolve({ status: res.statusCode, body: raw }); }
        });
      }
    );
    req.on("error", reject);
    req.write(data);
    req.end();
  });
}

// ── Main handler ─────────────────────────────────────────────
exports.handler = async (event) => {
  if (event.httpMethod !== "POST") {
    return { statusCode: 405, body: "Method Not Allowed" };
  }

  const apiKey = process.env.LOOPS_API_KEY;
  if (!apiKey) {
    console.error("LOOPS_API_KEY environment variable not set");
    return { statusCode: 500, body: "Server configuration error" };
  }

  try {
    // Parse form body
    const params = new URLSearchParams(event.body);
    const email  = (params.get("email") || "").trim().toLowerCase();
    const prefs  = params.getAll("preferences[]");

    // Honeypot check
    if (params.get("_honeypot")) {
      return { statusCode: 303, headers: { Location: "/?subscribed=true" }, body: "" };
    }

    if (!email || !email.includes("@")) {
      return { statusCode: 400, body: JSON.stringify({ error: "Invalid email" }) };
    }

    // Build contact properties
    const contactProps = { source: "emevidence.org website" };
    for (const pref of prefs) {
      if (PROPS[pref]) contactProps[PROPS[pref]] = true;
    }

    // Build list memberships
    const mailingLists = {};
    for (const pref of prefs) {
      if (LISTS[pref]) mailingLists[LISTS[pref]] = true;
    }

    // 1. Create or update contact in Loops
    const contactRes = await loopsPost("/contacts/create", {
      email,
      mailingLists,
      ...contactProps,
    }, apiKey);

    console.log("Loops contact create:", JSON.stringify(contactRes));

    // If contact already exists, update instead
    if (contactRes.status === 409 || (contactRes.body && contactRes.body.message && contactRes.body.message.includes("already exists"))) {
      const updateRes = await loopsPost("/contacts/update", {
        email,
        mailingLists,
        ...contactProps,
      }, apiKey);
      console.log("Loops contact update:", JSON.stringify(updateRes));
    }

    // 2. Send welcome transactional email
    const welcomeRes = await loopsPost("/transactional", {
      email,
      transactionalId: WELCOME_ID,
      addToAudience: true,
      dataVariables: {
        preferences: prefs.length > 0 ? prefs.join(", ") : "General updates",
      },
    }, apiKey);

    console.log("Loops welcome email:", JSON.stringify(welcomeRes));

    // 3. Redirect back with success flag
    return {
      statusCode: 303,
      headers: { Location: "/?subscribed=true" },
      body: "",
    };

  } catch (err) {
    console.error("Subscribe function error:", err);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: "Subscription failed. Please try again." }),
    };
  }
};
