// Tools data - EMEvidence
const tools = [
    // --- HIGHLIGHTED APPS (isNew: true puts a tool in the Highlighted Apps row) ---
    {
        id: "em-simulator",
        name: "Medical Simulation App",
        description: "Interactive emergency medicine simulation cases for training and self-directed learning — resuscitation, majors, and paediatric scenarios",
        category: "Simulation",
        tags: ["simulation", "training", "education", "cases", "resuscitation"],
        url: "https://wmebemsim.netlify.app/",
        featured: true,
        isNew: true,
        icon: "monitor",
        screenshot: "screenshots/em-simulator.png"
    },
    {
        id: "frcem-revision",
        name: "FRCEM & MRCEM Revision App",
        description: "Exam revision tool for FRCEM and MRCEM candidates — practice questions, OSCE preparation, and high-yield topic revision",
        category: "Education & Advisory",
        tags: ["FRCEM", "MRCEM", "revision", "exams", "OSCE", "training"],
        url: "https://frcemosceprep.netlify.app/",
        featured: true,
        beta: true,
        isNew: true,
        icon: "assessment",
        screenshot: "screenshots/frcem-revision.png"
    },
    // --- BEDSIDE AIDS (Cognitive aids for use at the bedside) ---
    {
        id: "als-app",
        name: "Cardiac Arrest App",
        description: "Real-time tool for managing and documenting actual cardiac arrest resuscitations in the emergency department",
        category: "Bedside Aids",
        tags: ["resuscitation", "cardiac", "ALS", "documentation", "real-time"],
        url: "https://wmebemals.netlify.app",
        featured: true,
        icon: "cardiac",
        screenshot: "screenshots/als-app.png"
    },
    {
        id: "major-trauma",
        name: "Major Trauma Management",
        description: "Complete app to run and document major trauma cases including primary and secondary survey protocols",
        category: "Bedside Aids",
        tags: ["trauma", "ATLS", "primary survey", "secondary survey", "documentation"],
        url: "https://majortrauma.netlify.app",
        featured: true,
        icon: "trauma",
        screenshot: "screenshots/major-trauma.png"
    },
    {
        id: "trauma-briefing",
        name: "Trauma Briefing & Zero Point",
        description: "Printable A3 poster for the trauma team brief and zero point survey before patient arrival (best printed or viewed on a large screen)",
        category: "Education & Advisory",
        tags: ["trauma", "briefing", "leadership", "zero point", "team"],
        url: "https://wmebemtraumabriefing.netlify.app",
        featured: true,
        icon: "trauma",
        screenshot: "screenshots/trauma-briefing.png"
    },
    {
        id: "back-pain-proforma",
        name: "Back Pain Proforma",
        description: "Low back pain assessment proforma for the Heartlands (BHH) and Good Hope (GHH) emergency departments",
        category: "UHB Tools",
        tags: ["documentation"],
        url: "https://bhhbackpain.netlify.app",
        featured: true,
        icon: "assessment",
        screenshot: "screenshots/back-pain.png"
    },
    {
        id: "sedation",
        name: "Procedural Sedation Tool",
        description: "Comprehensive tool to help plan, run, and document procedural sedation safely in the emergency department",
        category: "Bedside Aids",
        tags: ["sedation", "procedures", "safety", "documentation", "monitoring"],
        url: "https://sedation.netlify.app",
        featured: true,
        icon: "procedure",
        screenshot: "screenshots/sedation.png"
    },
    {
        id: "rsi-tool",
        name: "RSI Management Tool",
        description: "Structured tool to assist with planning, execution, and documentation of rapid sequence intubation in the ED",
        category: "Bedside Aids",
        tags: ["RSI", "airway", "intubation", "safety", "checklist"],
        url: "https://wmebemrsi.netlify.app",
        featured: true,
        icon: "airway",
        screenshot: "screenshots/rsi-tool.png"
    },
    {
        id: "rosc-management",
        name: "Post-ROSC Management",
        description: "Dedicated tool for the receipt and management of post-return of spontaneous circulation patients in the ED",
        category: "Bedside Aids",
        tags: ["cardiac", "resuscitation", "ROSC", "critical care"],
        url: "https://wmebemcardiacarrest.netlify.app",
        featured: false,
        icon: "cardiac",
        screenshot: "screenshots/rosc-management.png"
    },
    {
        id: "em-obstetrics",
        name: "Obstetric Emergencies",
        description: "Real-time cognitive aid for managing obstetric emergencies including PPH, eclampsia, and maternal resuscitation",
        category: "Bedside Aids",
        tags: ["obstetrics", "pregnancy", "emergency", "PPH", "resuscitation"],
        url: "https://emobstetrics.netlify.app",
        featured: true,
        icon: "procedure",
        screenshot: "screenshots/em-obstetrics.png"
    },
    {
        id: "sedation-agitated",
        name: "Agitated Patient Sedation",
        description: "Protocol for the safe sedation and management of patients with acute behavioural disturbance",
        category: "Bedside Aids",
        tags: ["sedation", "mental health", "agitated", "ABD", "safety"],
        url: "https://wmebemsedationagitated.netlify.app",
        featured: false,
        icon: "procedure",
        screenshot: "screenshots/sedation-agitated.png"
    },
    {
        id: "paeds-trauma-imaging",
        name: "Paeds Trauma Imaging",
        description: "Decision support tool for CT imaging in paediatric trauma based on latest Royal College of Radiology advice",
        category: "Bedside Aids",
        tags: ["paediatrics", "trauma", "imaging", "radiology", "CT"],
        url: "https://wmebempaedstraumaimaging.netlify.app",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/paeds-trauma.png"
    },
    {
        id: "visual-acuity",
        name: "Visual Acuity Screen",
        description: "Teaching guide for ED clinicians on how to test, interpret and document visual acuity, with a record builder and red flags",
        category: "Bedside Aids",
        tags: ["ophthalmology", "eyes", "vision", "assessment"],
        url: "https://wmebemvisualacuity.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/visual-acuity.png"
    },
    {
        id: "paed-first-seizure",
        name: "Paediatric First Seizure Assessment",
        description: "Structured assessment and documentation tool for children presenting with a first seizure, referencing NICE CG137 / NG217 and RCPCH guidance, with red-flag prompts and a pre-populated EPR note",
        category: "Bedside Aids",
        tags: ["paediatrics", "seizure", "epilepsy", "NICE", "RCPCH", "documentation", "red flags"],
        url: "https://paedfirstseizure.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/paed-first-seizure.png"
    },
    {
        id: "major-incident-triage",
        openInNewTab: true,
        name: "Major Incident Triage Tool",
        description: "Offline-capable app for triaging and documenting casualties in a major incident (TST and MITT), with patient handover by QR code, METHANE reporting and casualty register export",
        category: "Bedside Aids",
        tags: ["major incident", "triage", "TST", "MITT", "METHANE", "handover", "offline"],
        url: "https://majorincident.netlify.app",
        featured: false,
        icon: "trauma",
        screenshot: "screenshots/major-incident-triage.png"
    },
    {
        id: "uhb-side-room",
        name: "ED Side-Room Prioritisation (UHB, preliminary)",
        description: "PRELIMINARY DRAFT (v5, Oct 2026), for IPC review and not yet Trust-approved. Who gets the side room first when rooms run out in UHB EDs: priority ladder, two-patients-one-room rules, suspicion thresholds and de-isolation",
        category: "Bedside Aids",
        tags: ["isolation", "side room", "infection control", "IPC", "UHB", "preliminary"],
        url: "https://uhbsideroom.netlify.app",
        featured: false,
        beta: true,
        icon: "guidelines",
        screenshot: "screenshots/uhb-side-room.png"
    },

    // --- SIMULATION (For Training) ---
    {
        id: "incident-game",
        name: "Major Incident Game",
        description: "Interactive simulation game for training in major incident command, control, and triage",
        category: "Simulation",
        tags: ["major incident", "simulation", "triage", "command", "game"],
        url: "https://wmebemincident.netlify.app",
        featured: false,
        beta: true,
        icon: "trauma",
        screenshot: "screenshots/incident-game.png"
    },
    {
        id: "mass-casualty-triage",
        name: "Mass Casualty Triage",
        description: "Training application for mass casualty triage sorting using standard sieve and sort methods",
        category: "Simulation",
        tags: ["major incident", "triage", "training", "sieve", "sort"],
        url: "https://tstmitt.netlify.app",
        featured: false,
        icon: "trauma",
        screenshot: "screenshots/mass-casualty.png"
    },
    {
        id: "defib-sim",
        name: "Defibrillator Simulator",
        description: "Interactive defibrillator simulation tool for training in cardioversion, defibrillation, and external pacing",
        category: "Simulation",
        tags: ["simulation", "cardiac", "defibrillator", "pacing", "equipment"],
        url: "https://wmebemdefib.netlify.app",
        featured: false,
        icon: "defib",
        screenshot: "screenshots/defib-sim.png"
    },

    // --- EDUCATION & ADVISORY (Reference & Guidelines) ---
    {
        id: "paeds-guidelines",
        name: "Paediatric Guidelines 2025–28",
        description: "Searchable collection of paediatric guidelines, scores and calculators, with offline use, favourites and dark mode",
        category: "Education & Advisory",
        tags: ["paediatrics", "guidelines", "reference", "scores", "calculators", "offline"],
        url: "https://paedsguide.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/paeds-guidelines.png"
    },
    {
        id: "bhh-who-sees-who",
        name: "BHH Who Sees Who",
        description: "Which specialty sees which adult admission at Birmingham Heartlands Hospital, with searchable conditions and conflict-resolution principles",
        category: "UHB Tools",
        tags: ["guidelines", "BHH", "referrals", "workflow", "specialty"],
        url: "https://bhhwhoseeswho.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/bhh-who-sees-who.png"
    },
    {
        id: "consultant-ai",
        name: "Consultant AI Dashboard",
        description: "Educational site on ways medical consultants can utilise AI in their working lives",
        category: "Education & Advisory",
        tags: ["AI", "education", "productivity", "management", "tech"],
        url: "https://consultantaidashboard.netlify.app",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/consultant-ai.png"
    },
    {
        id: "qip-assist",
        isNew: true,
        name: "QIP Assist",
        description: "Interactive guide to help doctors design, execute and visualize RCEM Quality Improvement Projects",
        category: "Education & Advisory",
        tags: ["QIP", "audit", "governance", "education", "management"],
        url: "https://wmebemqipassist.netlify.app",
        featured: false,
        beta: true,
        icon: "guidelines",
        screenshot: "screenshots/qip-assist.png"
    },
    {
        id: "halo-qrh",
        isNew: true,
        name: "HALO QRH (Adults)",
        description: "Quick Reference Handbook for High Acuity, Low Occurrence (HALO) emergency procedures in patients aged 16 and over, with a preparation walkthrough and action card for each procedure. Based on DAS, RCEM, FPHC and Resuscitation Council UK guidance",
        category: "Education & Advisory",
        tags: ["resuscitation", "guidelines", "checklist", "HALO"],
        url: "https://wmebemhaloqrh.netlify.app",
        featured: false,
        beta: true,
        icon: "guidelines",
        screenshot: "screenshots/halo-qrh.png"
    },
    {
        id: "limping-child",
        name: "Limping Child Assessment",
        description: "Structured assessment and documentation tool for the limping child (NICE / RCEM), with red flags, Kocher criteria, differentials and a pre-populated EPR note",
        category: "Bedside Aids",
        tags: ["paediatrics", "orthopaedics", "limp", "septic arthritis", "pathway"],
        url: "https://paedlimpingchild.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/limping-child.png"
    },
    {
        id: "hyponatraemia",
        name: "Hyponatraemia Guide",
        description: "Interactive guide for the assessment and safe management of hyponatraemia in the emergency department",
        category: "Education & Advisory",
        tags: ["metabolic", "sodium", "guidelines", "endocrine"],
        url: "https://wmebemhyponatraemia.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/hyponatraemia.png"
    },
    {
        id: "af-in-the-ed",
        name: "AF in the ED",
        description: "Guide on managing new AF in the ED",
        category: "Education & Advisory",
        tags: ["guidelines", "cardiac"],
        url: "https://wmebemaf.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/af.png"
    },
    {
        id: "tloc-tool",
        name: "Syncope & TLOC Assessment",
        description: "Evidence-based risk stratification and investigation guidance for syncope and transient loss of consciousness",
        category: "Education & Advisory",
        tags: ["cardiac", "syncope", "neuro", "risk", "assessment"],
        url: "https://wmebemtloc.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/tloc-tool.png"
    },
    {
        id: "dvla-guide",
        name: "DVLA Driving Advice",
        description: "Up-to-date DVLA driving advice and regulations for a variety of medical conditions relevant to EM practice",
        category: "Education & Advisory",
        tags: ["DVLA", "legal", "discharge", "guidelines"],
        url: "https://wmebemdvla.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/dvla-guide.png"
    },
    {
        id: "omi-stemi",
        name: "OMI / STEMI Education",
        description: "Educational resource covering the new OMI (Occlusion MI) paradigm and STEMI recognition",
        category: "Education & Advisory",
        tags: ["cardiac", "ECG", "education", "STEMI", "OMI"],
        url: "https://wmebemstemitoomi.netlify.app",
        featured: false,
        icon: "cardiac",
        screenshot: "screenshots/omi.png"
    },
    {
        id: "fluid-sid",
        name: "Acid–Base & Fluids Sandbox",
        description: "Teaching site covering traditional, base excess and Stewart (SID) acid-base analysis, where IV fluids go, UK crystalloid compositions, simulators, a calculator and worked cases",
        category: "Education & Advisory",
        tags: ["resuscitation", "metabolic", "fluids", "education"],
        url: "https://wmebemsid.netlify.app/",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/fluid-sid.png"
    },
    {
        id: "hot-joint",
        name: "Hot Joint Education",
        description: "Educational resource covering the assessment, investigation, and management of the hot swollen joint",
        category: "Education & Advisory",
        tags: ["orthopaedics", "septic arthritis", "joint", "education"],
        url: "https://wmebemhotjoint.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/hot-joint.png"
    },
    {
        id: "antiemetics",
        name: "Antiemetics Guidance",
        description: "Evidence-based advice and guidance on antiemetic selection and dosing for various presentations",
        category: "Education & Advisory",
        tags: ["pharmacology", "guidelines", "vomiting"],
        url: "https://wmebemantiemetics2.netlify.app",
        featured: false,
        icon: "procedure",
        screenshot: "screenshots/antiemetics.png"
    },
    {
        id: "triage-app",
        name: "Experimental Triage",
        description: "Experimental digital triage support tool for initial patient assessment and categorization",
        category: "Education & Advisory",
        tags: ["triage", "assessment", "experimental"],
        url: "https://wmebemtriage.netlify.app",
        featured: false,
        beta: true,
        icon: "assessment",
        screenshot: "screenshots/triage.png"
    },
    {
        id: "box-breathing",
        name: "Box Breathing App",
        description: "Visual pacing tool for box breathing techniques to manage stress, anxiety, and performance",
        category: "Education & Advisory",
        tags: ["wellbeing", "stress", "mental health"],
        url: "https://wmebemboxbreathing.netlify.app/",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/box-breathing.png"
    },
    {
        id: "ct-risk",
        name: "CT Risk in Children",
        description: "Educational summary and critical appraisal regarding radiation risk and malignancy from CT scans in children",
        category: "Journal Club",
        tags: ["paediatrics", "radiology", "risk", "education"],
        url: "https://wmebemctrisk.netlify.app",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/ct-risk.png"
    },
    {
        id: "sedation-edu",
        name: "Sedation Education",
        description: "Educational modules covering pharmacology, safety, and techniques for procedural sedation",
        category: "Education & Advisory",
        tags: ["sedation", "education", "training"],
        url: "https://wmebemsedation.netlify.app",
        featured: false,
        icon: "procedure",
        screenshot: "screenshots/sedation-edu.png"
    },
    {
        id: "dvla-poster",
        name: "DVLA Advice Poster",
        description: "Quick-reference visual poster summarizing common DVLA driving restrictions for ED patients",
        category: "Education & Advisory",
        tags: ["DVLA", "legal", "poster", "reference"],
        url: "https://dvlaemposter.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/dvla-poster.png"
    },
    {
        id: "pericardiocentesis",
        name: "Emergency Pericardiocentesis",
        description: "Comprehensive guide to the emergency medicine approach to pericardiocentesis including indications and technique",
        category: "Education & Advisory",
        tags: ["procedures", "cardiac", "guide"],
        url: "https://wmebempericardiocentesis.netlify.app",
        featured: false,
        icon: "procedure",
        screenshot: "screenshots/pericardiocentesis.png"
    },
    {
        id: "teg-edu",
        name: "Viscoelastic Testing (TEG)",
        description: "Training and education on viscoelastic testing in emergency and critical care",
        category: "Education & Advisory",
        tags: ["TEG", "viscoelastic", "haematology", "bleeding", "education"],
        url: "https://wmebemteg.netlify.app",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/teg.png"
    },
    {
        id: "dog-bites",
        name: "Dog Bite Management",
        description: "Guidance on the assessment and management of dog bites in the emergency department",
        category: "Education & Advisory",
        tags: ["trauma", "wounds", "bites", "infection", "guidelines"],
        url: "https://wmebemdogbites.netlify.app",
        featured: false,
        icon: "procedure",
        screenshot: "screenshots/dog-bites.png"
    },
    {
        id: "ai-for-em",
        name: "AI for EM Clinicians",
        description: "Educational website teaching emergency medicine clinicians how to use artificial intelligence for portfolios, research, and critical appraisal",
        category: "Education & Advisory",
        tags: ["AI", "education", "research", "portfolio", "appraisal"],
        url: "https://wmebemaiforem.netlify.app",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/ai-for-em.png"
    },
    // --- BEDSIDE AIDS (added Oct 2026) ---
    {
        id: "paed-wheeze",
        name: "Paediatric Wheeze Assessment",
        description: "Structured assessment and documentation tool for children with wheeze (BTS/SIGN 2024, NICE NG80), covering severity, treatment, response and disposition, with a pre-populated EPR note",
        category: "Bedside Aids",
        tags: ["paediatrics", "asthma", "wheeze", "respiratory", "documentation"],
        url: "https://paedwheeze.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/paed-wheeze.png",
        isNew: true
    },
    {
        id: "paed-mental-health",
        name: "Paediatric Mental Health Assessment",
        description: "Structured assessment for children and young people presenting with mental health concerns (RCPCH / NICE), covering safeguarding, HEADSSS, mental state examination, risk and plan",
        category: "Bedside Aids",
        tags: ["paediatrics", "mental health", "safeguarding", "HEADSSS", "risk assessment"],
        url: "https://paedmhassessment.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/paed-mental-health.png",
        isNew: true
    },
    {
        id: "paeds-halo-qrh",
        name: "HALO QRH (Paediatrics)",
        description: "Paediatric edition of the HALO Quick Reference Handbook for patients under 16, including neonates: 13 high acuity, low occurrence procedures with WETFLAG reference. Based on Resuscitation Council UK 2025, DAS 2025 and RCOG guidance",
        category: "Bedside Aids",
        tags: ["HALO", "paediatrics", "procedures", "QRH", "resuscitation"],
        url: "https://paediatrichaloqrh.netlify.app",
        featured: false,
        icon: "procedure",
        screenshot: "screenshots/paeds-halo-qrh.png",
        isNew: true
    },

    // --- UHB TOOLS (University Hospitals Birmingham: BHH, GHH, QEHB, Solihull) ---
    {
        id: "bhh-mhp",
        name: "BHH Major Haemorrhage Procedure",
        description: "Emergency department quick reference poster for activating and running the major haemorrhage procedure",
        category: "UHB Tools",
        tags: ["major haemorrhage", "transfusion", "trauma", "poster", "BHH"],
        url: "https://bhhmhp.netlify.app",
        featured: false,
        icon: "trauma",
        screenshot: "screenshots/bhh-mhp.png"
    },
    {
        id: "uhb-pe",
        name: "UHB PE Guideline",
        description: "Interactive version of the University Hospitals Birmingham pulmonary embolism guideline (CG062): diagnosis, Wells score, thrombolysis, low-risk PE and anticoagulation",
        category: "UHB Tools",
        tags: ["PE", "pulmonary embolism", "anticoagulation", "thrombolysis", "UHB"],
        url: "https://uhbpe.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/uhb-pe.png"
    },
    {
        id: "bhh-halo-handbook",
        name: "BHH HALO Handbook",
        description: "Birmingham Heartlands resus area handbook for High Acuity, Low Occurrence procedures, with a team brief script and procedure pages",
        category: "UHB Tools",
        tags: ["HALO", "procedures", "resus", "BHH", "handbook"],
        url: "https://wmebemhalo.netlify.app",
        featured: false,
        icon: "procedure",
        screenshot: "screenshots/bhh-halo-handbook.png"
    },
    {
        id: "bhh-handover",
        name: "BHH ED Handover",
        description: "Structured daily ED handover prompt for Birmingham Heartlands, with handover teaching, alerts and night handover (landscape screen format)",
        category: "UHB Tools",
        tags: ["handover", "BHH", "safety", "teaching"],
        url: "https://bhhhandover.netlify.app",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/bhh-handover.png",
        openInNewTab: true
    },

    // --- EDUCATION & ADVISORY (added Oct 2026) ---
    {
        id: "niv-hamilton-t1",
        name: "NIV Training: Hamilton T1",
        description: "Interactive training aid for doctors and nurses on non-invasive ventilation with the Hamilton T1: pre-use checks, set-up, modes, alarms, troubleshooting and practice scenarios",
        category: "Education & Advisory",
        tags: ["NIV", "ventilation", "Hamilton T1", "respiratory", "training"],
        url: "https://wmebemniv.netlify.app",
        featured: false,
        icon: "airway",
        screenshot: "screenshots/niv-hamilton-t1.png",
        isNew: true
    },
    {
        id: "regional-anaesthesia",
        name: "Regional Anaesthesia Guide",
        description: "Body-map guide to ED nerve blocks, with indications, equipment, volumes, maximum safe local anaesthetic doses, LAST management and patient advice",
        category: "Education & Advisory",
        tags: ["nerve blocks", "regional anaesthesia", "analgesia", "LAST", "ultrasound"],
        url: "https://emplanablocks.netlify.app",
        featured: false,
        icon: "procedure",
        screenshot: "screenshots/regional-anaesthesia.png",
        isNew: true
    },
    {
        id: "head-injury",
        name: "Head Injury Pathway",
        description: "Interactive guide to head injury assessment and management in UK emergency departments, based on NICE guidance",
        category: "Education & Advisory",
        tags: ["head injury", "trauma", "NICE", "CT", "neurology"],
        url: "https://wmebemhi.netlify.app",
        featured: false,
        icon: "trauma",
        screenshot: "screenshots/head-injury.png"
    },
    {
        id: "obs-gynae-emergencies",
        name: "Obstetric & Gynae Emergencies",
        description: "Quick reference and documentation tool for obstetric and gynaecological emergencies in the ED, from amniotic fluid embolism to shoulder dystocia",
        category: "Education & Advisory",
        tags: ["obstetrics", "gynaecology", "emergencies", "PPH", "ectopic"],
        url: "https://wmebemobsandgynae.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/obs-gynae.png"
    },
    {
        id: "heat-illness",
        name: "Heat-Related Illness",
        description: "Interactive guide to the diagnosis and management of heat illness and heat stroke in UK emergency departments",
        category: "Education & Advisory",
        tags: ["heat stroke", "hyperthermia", "environmental", "cooling"],
        url: "https://wmebemheatwebsite.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/heat-illness.png"
    },
    {
        id: "aortic-dissection",
        name: "Acute Aortic Dissection",
        description: "Infographic on recognising and diagnosing acute aortic dissection in the ED, a high-stakes chest pain mimic",
        category: "Education & Advisory",
        tags: ["aortic dissection", "chest pain", "cardiovascular", "diagnosis"],
        url: "https://wmebemaad.netlify.app",
        featured: false,
        icon: "cardiac",
        screenshot: "screenshots/aortic-dissection.png"
    },
    {
        id: "delirium",
        name: "Delirium in the ED",
        description: "High-yield infographic on recognising and managing delirium in older ED patients, including hypoactive delirium",
        category: "Education & Advisory",
        tags: ["delirium", "older people", "geriatrics", "cognition"],
        url: "https://wmebemdelirium.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/delirium.png"
    },
    {
        id: "hypothermia",
        name: "Hypothermia",
        description: "Infographic on accidental hypothermia: Swiss staging, rewarming and hypothermic cardiac arrest",
        category: "Education & Advisory",
        tags: ["hypothermia", "environmental", "rewarming", "cardiac arrest"],
        url: "https://wmebemhypothermia.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/hypothermia.png"
    },
    {
        id: "dka",
        name: "Diabetic Ketoacidosis",
        description: "In-depth guide to the pathophysiology and ED management of diabetic ketoacidosis",
        category: "Education & Advisory",
        tags: ["DKA", "diabetes", "endocrine", "ketones", "acid-base"],
        url: "https://wmebemdka.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/dka.png"
    },
    {
        id: "ketoacidosis",
        name: "Ketoacidosis in the ED",
        description: "Practical infographic on ketone bodies, how they are measured, and the causes of ketoacidosis beyond DKA",
        category: "Education & Advisory",
        tags: ["ketones", "ketoacidosis", "acid-base", "endocrine"],
        url: "https://wmebemketones.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/ketoacidosis.png"
    },
    {
        id: "lactate",
        name: "Lactic Acidosis",
        description: "Interactive dashboard on lactic acidosis: physiology, type A and B causes, anion gap and delta ratio calculator, and management",
        category: "Education & Advisory",
        tags: ["lactate", "acid-base", "sepsis", "shock"],
        url: "https://wmebemlactate.netlify.app",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/lactate.png"
    },
    {
        id: "blood-gas-analysers",
        name: "How Blood Gas Analysers Work",
        description: "Interactive guide to blood gas analysers: what they measure, how, and the pitfalls that matter in the ED",
        category: "Education & Advisory",
        tags: ["blood gas", "ABG", "VBG", "acid-base", "laboratory"],
        url: "https://wmebemgasanalyser.netlify.app",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/blood-gas-analysers.png"
    },
    {
        id: "vq-mismatch",
        name: "V/Q Mismatch Explorer",
        description: "Animated explainer of ventilation-perfusion matching, shunt, dead space and West zones",
        category: "Education & Advisory",
        tags: ["physiology", "respiratory", "V/Q", "hypoxia"],
        url: "https://wmebemvq.netlify.app",
        featured: false,
        icon: "airway",
        screenshot: "screenshots/vq-mismatch.png"
    },
    {
        id: "pocus-guide",
        name: "POCUS Guide for EM Registrars",
        description: "Interactive guide to point-of-care ultrasound for EM registrars, mapped to the RCEM curriculum, with probe selection and core applications",
        category: "Education & Advisory",
        tags: ["POCUS", "ultrasound", "training", "RCEM"],
        url: "https://wmemussapp.netlify.app",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/pocus-guide.png"
    },
    {
        id: "confidentiality",
        name: "Confidentiality in EM",
        description: "Quick reference on patient confidentiality in UK emergency medicine: when you must, may and must not disclose",
        category: "Education & Advisory",
        tags: ["confidentiality", "GMC", "law", "ethics", "DVLA", "police"],
        url: "https://wmebemconfidentiality.netlify.app",
        featured: false,
        icon: "guidelines",
        screenshot: "screenshots/confidentiality.png"
    },
    {
        id: "risk-communication",
        name: "Risk Communication Tool",
        description: "Visualise test performance, absolute and relative risk, NNT/NNH and Bayesian probabilities to explain risk to patients",
        category: "Education & Advisory",
        tags: ["risk", "shared decision making", "statistics", "NNT", "Bayes"],
        url: "https://wmebemdata.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/risk-communication.png"
    },
    {
        id: "bayesian-reasoning",
        name: "Bayesian vs Frequentist Reasoning",
        description: "Guide to the two main ways of reasoning about uncertainty in medical evidence, with clinical analogies",
        category: "Education & Advisory",
        tags: ["statistics", "Bayesian", "evidence", "critical appraisal"],
        url: "https://wmebembayesian.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/bayesian.png"
    },
    {
        id: "wellness-hub",
        name: "EM Wellness Hub",
        description: "Practical toolkit for career sustainability and wellbeing in UK emergency medicine, with UK support resources",
        category: "Education & Advisory",
        tags: ["wellbeing", "burnout", "career", "support"],
        url: "https://wmebemwellnesshub.netlify.app",
        featured: false,
        icon: "monitor",
        screenshot: "screenshots/wellness-hub.png"
    },

    // --- JOURNAL CLUB (critical appraisals and evidence summaries) ---
    {
        id: "abc-sepsis",
        name: "ABC-Sepsis Trial",
        description: "Critical appraisal of the ABC-Sepsis trial: 5% human albumin solution versus balanced crystalloid for fluid resuscitation in ED sepsis",
        category: "Journal Club",
        tags: ["sepsis", "albumin", "fluids", "RCT", "FRCEM"],
        url: "https://wmebemabcsepsis.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/abc-sepsis.png"
    },
    {
        id: "espb-rib-fractures",
        name: "ESP Block for Rib Fractures",
        description: "Critical appraisal of a study of ultrasound-guided erector spinae plane block for traumatic rib fractures in the ED",
        category: "Journal Club",
        tags: ["nerve blocks", "rib fractures", "analgesia", "trauma"],
        url: "https://wmebemespb.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/espb.png"
    },
    {
        id: "colles-nerve-blocks",
        name: "Nerve Blocks for Colles' Fractures",
        description: "Critical appraisal of a Danish multicentre trial of ultrasound-guided nerve blocks versus haematoma block for Colles' fracture reduction",
        category: "Journal Club",
        tags: ["nerve blocks", "fractures", "analgesia", "ultrasound"],
        url: "https://wmebemhbvsuss.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/colles.png"
    },
    {
        id: "furosemide-adhf",
        name: "IV Furosemide in Heart Failure",
        description: "Critical appraisal of Harrison et al. (2025): how much does IV furosemide lower blood pressure in acute decompensated heart failure?",
        category: "Journal Club",
        tags: ["heart failure", "furosemide", "diuretics", "cardiology"],
        url: "https://wmebemfurosemide.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/furosemide.png"
    },
    {
        id: "ketamine-propofol-tbi",
        name: "Ketamine vs Propofol for RSI in TBI",
        description: "Evidence summary comparing ketamine and propofol as induction agents for RSI in traumatic brain injury",
        category: "Journal Club",
        tags: ["RSI", "TBI", "ketamine", "propofol", "airway"],
        url: "https://wmebemrsihi.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/ketamine-propofol.png"
    },
    {
        id: "mannitol-hts",
        name: "Mannitol vs Hypertonic Saline",
        description: "Visual evidence summary comparing mannitol and hypertonic saline for raised intracranial pressure",
        category: "Journal Club",
        tags: ["ICP", "TBI", "mannitol", "hypertonic saline", "neurocritical care"],
        url: "https://wmebemhtsvsmannitol.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/mannitol-hts.png"
    },
    {
        id: "neurocardiac-axis",
        name: "The Neurocardiac Axis in TBI",
        description: "Evidence summary on cardiac complications of traumatic brain injury",
        category: "Journal Club",
        tags: ["TBI", "cardiac", "trauma", "neurocritical care"],
        url: "https://wmebemneurocardiacaxis.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/neurocardiac.png"
    },
    {
        id: "nibp-iabp",
        name: "NIBP vs Invasive BP",
        description: "Visual guide to the differences between non-invasive and invasive arterial blood pressure monitoring",
        category: "Journal Club",
        tags: ["blood pressure", "monitoring", "arterial line", "physiology"],
        url: "https://wmebemnibpvsaline.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/nibp-iabp.png"
    },
    {
        id: "admission-rates",
        name: "The Admission Lottery?",
        description: "Summary of a study of variation in ED physician admitting practices and subsequent mortality",
        category: "Journal Club",
        tags: ["admissions", "variation", "mortality", "health services"],
        url: "https://wmebemadmissionrates.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/admission-rates.png"
    },
    {
        id: "andromeda-shock-2",
        name: "ANDROMEDA-SHOCK-2",
        description: "Summary of the ANDROMEDA-SHOCK-2 trial (JAMA, 2025): capillary refill time-targeted resuscitation in early septic shock",
        category: "Journal Club",
        tags: ["sepsis", "septic shock", "capillary refill", "resuscitation", "RCT"],
        url: "https://wmebemandromeda2.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/andromeda-shock-2.png"
    },
    {
        id: "em-pharmacotherapy-2024",
        name: "EM Pharmacotherapy 2024",
        description: "Infographic summary of the key emergency medicine pharmacotherapy guidelines, trials and meta-analyses of 2024",
        category: "Journal Club",
        tags: ["pharmacology", "drugs", "literature review", "2024"],
        url: "https://empharmacotherapy2024.netlify.app",
        featured: false,
        icon: "assessment",
        screenshot: "screenshots/em-pharmacotherapy-2024.png"
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = tools;
}
